#!/bin/bash

printf "Autoremove files which was generated by LaTeX\n"
printf "    with {.aux, .fdb_latexmk, .fls, .log, .out, .xdv, .nav, .snm, .toc, .sta, .synctex.gz} extensions\n"
printf "\n"

find . \( -iname "*.aux" -o -iname "*.fdb_latexmk" \
    -o -iname "*.fls" -o -iname "*.log" -o -iname "*.out" -o -iname "*.xdv" \
    -o -iname "*.nav" -o -iname "*.snm" -o -iname "*.toc" \
    -o -iname "*.sta" -o -iname "*.synctex.gz" \) \
    -exec rm {} \;

printf "By KonstantIMP <konstantimp@yandex.ru>\n"
